### ISSUE TITLE
Branch for GitHub Pages not being updated with new projects

### ISSUE THREAD

**Issue by oxr463** [firstcontributions/firstcontributions.github.io#44]
@Roshanjossey, @sara-02 this was pushed, but the `gh-pages` branch does not look like it has been updated.

_Originally posted by @oxr463 in https://github.com/firstcontributions/firstcontributions.github.io/pull/40#issuecomment-469096436_

**Comment by sara-02** [comment]
IMHO I don't think it is an issue with GH pages. GH pages branch only provide the placeholder for the project list, the issue seems to be with deployment. Once the new deployment is run, it should pick the latest list of projects and you should see PRoot being listed.
@Roshanjossey can shed more light on it.

**Comment by oxr463** [comment]
Has the new deployment been run yet?

**Comment by sara-02** [comment]
ping @Roshanjossey maybe you could help answer this one.

**Comment by Roshanjossey** [comment]
Hi, sorry that I've been away for some time. I've deployed the latest version yesterday.

I think it's high time we setup CI for this.

@sara-02 , if you're interested in knowing how deployment works, I'll put more information here. You should also have access to deploy

**Comment by sara-02** [comment]
@Roshanjossey Sure will get in touch with you regarding that.

**Comment by sara-02** [comment]
BTW looks like we can close this. @oxr463 please reopen it if the changes you are expecting are not visible yet.
