### ISSUE TITLE
Should we move to `/contribute` link for all projects

### ISSUE THREAD

**Issue by Roshanjossey** [firstcontributions/firstcontributions.github.io#76]
Discuss the benefits and drawbacks for using `repo-link/contribute` provided by GitHub instead of issue filters we have.

This is the [issue ](https://github.com/firstcontributions/first-contributions/issues/19133) that suggested this change 

This is the [pull request](https://github.com/firstcontributions/firstcontributions.github.io/pull/58) that made the require changes.

This is a [comment](https://github.com/firstcontributions/firstcontributions.github.io/pull/58#issuecomment-538285156) in the pull request suggesting that this might not be at the best interest of users.

@sara-02 , @gavv , @tiferet, shall we discuss and figure this out?

**Comment by sara-02** [comment]
Even I need to read how the /contribute attribute works, lets sync on this once we have an idea about its working, then we can see if it works for a majority of the cases or not.

**Comment by tiferet** [comment]
Happy to share any insights into /contribute and discuss...

**Comment by sara-02** [comment]
@tiferet Sure, please let us know your findings. Honestly I am clueless about its working ATM

**Comment by tiferet** [comment]
I'm working on it at GitHub, so I can explain whatever you want.

**Comment by sara-02** [comment]
Do we have any blog posts or links where we can read about it working and/or get an overview of it.

**Comment by tiferet** [comment]
Not yet. We're shipping a major new version soon and will write about it then. 

Right now it's a very simple algorithm. Basically it just surfaces all issues that have any of about 300 labels we've identified as be synonyms for either `good first issue` or `documentation`. It ranks them both by the relevance of their labels and by their recency.

The next version will try to surface additional issues that haven't been manually labeled, but will still uprank all the issues that do have these labels.

I think [the problem @gavv had](https://github.com/firstcontributions/firstcontributions.github.io/pull/73) was specific to that project, where they use the the `help wanted` label instead of `good first issue` or one of its synonyms. We've purposely kept `help wanted` out of the list, because the feedback we got from maintainers was that it often indicates a harder issue, that needs more extensive work, and not at all a beginner-friendly issue.

One option would be to just revert to a manual filter specifically for the Roc repo, and keep the `/contribute` link for most repos, which do use the labels on our list.

Incidentally, if anyone has labels they use that they would like to see added to the list, we can look into doing that, but the `help wanted` label in particular seems to be problematic for many repos....

**Comment by gavv** [comment]
@tiferet BTW, in case of our project, listing documentation issues as good for contributors is not a good idea. These issues usually require in-depth knowledge about internals. Probably this is true for some other projects as well.

**Comment by Roshanjossey** [comment]
Thank you for participating in the discussion @tiferet, @gavv.

I went through `/contribute` links and I'm happy with them. I hope `help wanted` labels will be a part of this in the future.

@sara-02, I think we can continue with `/contribute` and make changes if the maintainers suggests them.

If you're happy, let's close this issue.

**Comment by sara-02** [comment]
@Roshanjossey sure. We can keep `/contribute` for consistency. And add exceptions on a case basis.
We should add this as a note in the how-to contribute section for the web app, so that people know when and where to add use `/contribute`
